= Apache James parent project
OpenPaas Team <lgs-openpaas-dev@linagora.com>;
:imagesdir: images
:numbered:
:sectlink:
:sectids:
:toc: left
:toclevels: 2
:icons: font

== About

The main goal of this project is to provide a maven based parent project to +Apache James+. +
So, building phase may be checked with a single command.


== Building in Docker

[NOTE]
====
You need to install https://docs.docker.com[+docker+] before going ahead. +
Please follow the installation process corresponding to your environment.
====

=== Build the Docker image

[source]
----
$ docker build -t james/parent .
----

=== Run the build in Docker

In order to run the build, you have to launch the following command:

[source]
----
$ docker run -v $PWD/.m2:/root/.m2 -v $PWD:/origin -v $PWD/destination:/destination -t james/parent -s -u URL BRANCH
----

Where:

- +$PWD/.m2:/root/.m2+: is the first volume used to share the +maven+ repository, +
as we don't want to download all dependencies on each build
- +$PWD/destination:/destination+: is the third volume used to get the compiled elements, +
as it is needed by the container that will run James.
- +BRANCH+: is the given +git+ branch of the +james-parent+ repository to build
- +-s option+: given tests will not be played while building. Not specifying means play tests.
- +-u URL+: Precise URL to clone. Default is to use /origin docker folder. In this case you have to provide the following volume :
   - +$PWD:/origin+: is the second volume used to share the +james-parent+ repository, +
as we don't want to clone it in docker

Note : Using volumes on a distant host will not work. You can simply use the distant option :

[source]
----
$ docker run -v /destination -t james/parent  -s -u https://ci.open-paas.org/stash/scm/jwc/james-parent.git BRANCH
----

== Running James in docker

==== Requirements

You should have the zip resulting of the build in the ./destination folder.

==== How to ?

You need a running cassandra in docker. To achieve this run :

[source]
----
$ docker run --name=cassandra cassandra
----

We need to provide the key we will use for TLS. For obvious reasons, this is not provided in this git.

Copy your TSL keys to destination/conf/keystore or generate it using :

[source]
----
keytool -genkey -alias james -keyalg RSA -keystore destination/conf/keystore
----

Then we need to build james container :

[source]
----
$ docker build -f JamesRunDockerfile -t james_run ./
----

To run this container :

[source]
----
$ docker run --hostname HOSTNAME -p "25:25" -p "110:110" -p "143:143" -p "465:465" -p "587:587" -p "993:993" --link cassandra:cassandra -t james_run
----

Where :

- +HOSTNAME+ is the hostname you want to give to your James container. This DNS entry will be used to send mail to your James server.

=== Useful commands

==== How to add a domain ?

[source]
----
# Add DOMAIN to 127.0.0.1 in your host /etc/hosts
$ docker exec JAMES_CONTAINER_ID /root/james-server-app-3.0.0-beta5-SNAPSHOT/bin/james-cli.sh -h 127.0.0.1 -p 9999 adddomain DOMAIN
----

Where :

- +DOMAIN+ is the domain you want to add.
- +JAMES_CONTAINER_ID+ is the docker ID of your james container.

==== How to add a user ?

[source]
----
$ docker exec JAMES_CONTAINER_ID /root/james-server-app-3.0.0-beta5-SNAPSHOT/bin/james-cli.sh -h 127.0.0.1 -p 9999 adduser USER_MAIL_ADDRESS PASSWORD
----

Where :

- +USER_MAIL_ADDRESS+ is the mail address that will be used by this user.
- +PASSWORD+ is the password that will be used by this user.
- +JAMES_CONTAINER_ID+ is the docker ID of your james container

You can then just add DOMAIN to your /etc/hosts and you can connect to your james account with for instance thunderbird.

==== How to manage SIEVE scripts ?

Each user can manage his SIEVE scripts threw the manage SIEVE mailet.

To use the manage SIEVE mailet :

 - You need to create the user sievemanager@DOMAIN ( if you don't, the SMTP server will check the domain, recognize it, and look for an absent local user, and will generate an error ).
 - You can send Manage Sieve commands by mail to sievemanager@DOMAIN. Your subject must contain the command. Scripts needs to be added as attachments and need the ".sieve" extension.

To activate a script for a user, you need the following combinaison :

 - PUTSCRIPT scriptname
 - SETACTIVE scriptname

==== I want to retrieve users and password from my previous container

Some james data ( those non related to mailbox, eg : mail queue, domains, users, rrt, SIEVE scripts, mail repositories ) are not yet supported by our Cassandra implementation.

To keep these data when you run a new container, you can mount the following volume :

[source]
----
 -v /root/james-server-app-3.0.0-beta5-SNAPSHOT/var:WORKDIR/destination/var
----

Where :

- +WORKDIR+ is the absolute path to your james-parent workdir.

Beware : you will have concurrency issues if multiple containers are running on this single volume.

== Under the hood

Other +Apache James+ projects are linked to this project by using +git+ submodules.

The following commands will give you a working state for the given +git+ branch:
[source]
----
$ git checkout BRANCH
$ git submodule init
$ git submodule update
----

